<?php
    $detailCarts = $block->getAllItems();
    $totalQty = $block->getItemsSummaryQty();
    $subTotal = $block->getSubTotal();
    $grandTotal = $block->getGrandTotal();
?>

<input type="hidden" name="totalCart" id="totalCart" value="<?=$grandTotal?>" />

<div class="tit-page">
    <h2><?=__('your order')?></h2>
</div>
<div class="result-confirm">
    <div><?=__('Quantity')?>: <span class="total-qty"><?=number_format($totalQty)?></span></div>
    <div class="text-right">
        <div>
            <?=__('Sub total')?>: <span class="total_amount"><?=number_format($subTotal)?> vnđ</span>
        </div>
        <div>
            <?=__('Grand Total')?>: <span class="total_amount"><?=number_format($grandTotal)?> vnđ</span>
        </div>
    </div>
</div>

<div class="wrap-confirm">
    <?php foreach($detailCarts as $k => $item) { $price = intval($item->getPrice()); ?>
        <?php $urlDetailProduct = $block->getUrlDetailProduct($item->getProductId()); ?>
        <div class="it">
            <div>
                <a href="<?=$urlDetailProduct?>">
                    <img class="img-fluid" src="<?=$block->getDetailProduct($item->getSku(), 'thumbnail-cart')?>" alt="<?=$item->getName()?>" title="<?=$item->getName()?>"/>
                    
                    <?php if($price > 0){?>
                        <input type="hidden" name="product_id[]" value="<?=$item->getProductId()?>" />
                    <?php } ?>
                </a>
            </div>
            <div>
                <a href="<?=$urlDetailProduct?>"><?=$item->getName()?></a>
                <div class="confirm-number">
                    <div>
                        <select class="form-control item-qty-confirm-cart" <?php echo ($price > 0) ? '' : 'disabled' ?> name="qty[]" data-id="<?=$item->getId()?>">
                            <?php for($i=1; $i< 51; $i++){?>
                                <option <?=($i == $item->getQty()) ? 'selected' : ''?> value="<?=$i?>"><?= $i<10 ? '0'.$i : $i ?></option>
                            <?php } ?>
                        </select>
                    </div>
                    <div>
                        x <?=number_format($item->getPrice())?> VNĐ = <strong><?=number_format($item->getPrice() * $item->getQty())?> VNĐ</strong>
                    </div>
                </div>
            </div>

            <?php if($price > 0){?>
                <a class="remove-confirm" data-qty="0" data-id="<?=$item->getId()?>" href="javascript:void(0)">x</a>
            <?php } ?>
        </div>
    <?php } ?>
</div>