<?php
    $productCollections = $block->getProductsByCategory();
    $productTotal = $block->getProductsByCategory(true);
    $lastPageNumber = $productCollections->getLastPageNumber();
    $catRootProd = $block->getCategoryRootProduct();

    $currentCategory = $block->getCurrentCategory();
?>

<section>
    <div class="container">
        <div class="row text-center">
            <div class="col-12 col-sm-12 col-md-12 col-lg-12 col-xl-12">
                <nav class="nav-page">
                    <ol class="list-unstyled">
                        <li><a href="<?=$block->getBaseUrl()?>"><?=__('Home')?></a></li>
                        <li class="active"><?=__('Products')?></li>
                    </ol>
                </nav>
            </div>

            <div class="col-12 col-sm-12 col-md-12 col-lg-12 col-xl-12">
                <div class="product-page">
                    <!-- Block Top Brand -->
                    <?= $this->getLayout()->createBlock('DrinksAndCo\CustomizeProduct\Block\Brand')->setTemplate('brand/top.phtml')->toHtml(); ?>

                    <div class="row">
                        <div class="col-12 col-sm-12 col-md-4 col-lg-3 col-xl-3">
                            <form action="<?=$block->getUrlCategory()?>" method="get" class="auto-submit">
                                <section class="attribute-search">
                                    <input name="keyword" value="<?=$block->_request->getParam('keyword')?>" class="form-control" placeholder="<?=__('Find your taste')?>" type="text"/>
                                    <button type="submit" class="btn"><i class="fa fa-search" aria-hidden="true"></i></button>
                                </section>

                                <?php
                                    include ($block->getTemplateFile('DrinksAndCo_CustomizeProduct::product/attribute-product.phtml'));
                                    include ($block->getTemplateFile('DrinksAndCo_CustomizeProduct::product/recent-product.phtml'));
                                ?>
                            </form>
                        </div>

                        <div class="col-12 col-sm-12 col-md-8 col-lg-9 col-xl-9">
                            <div class="result-product">
                                <div class="row">
                                    <div class="col-md-6"><?=number_format($productTotal)?> <?=__('products')?></div>

                                    <?php if($catRootProd && $catRootProd->getChildrenCategories()){?>
                                        <div class="col-md-6 text-right">
                                            <?=__('Filter by category')?>:
                                            <select name="filter_prod_by_cat" id="filter_prod_by_cat">
                                                <option></option>
                                                <?php foreach($catRootProd->getChildrenCategories() as $item){?>
                                                    <option value="<?=$block->getUrlFilter($item->getUrlKey())?>"
                                                        <?=($currentCategory == $item->getUrlKey()) ? 'selected' : ''?>>
                                                        <?=$item->getName()?>
                                                    </option>
                                                    <?php 
                                                        if($item->getChildrenCategories()){
                                                            foreach($item->getChildrenCategories() as $item1){
                                                                ?>
                                                                    <option value="<?=$block->getUrlFilter($item1->getUrlKey())?>"
                                                                        <?=($currentCategory == $item1->getUrlKey()) ? 'selected' : ''?>>
                                                                        --- <?=$item1->getName()?>
                                                                    </option>

                                                                    <?php
                                                                        if($item1->getChildrenCategories()){
                                                                            foreach($item1->getChildrenCategories() as $item2){
                                                                                ?>
                                                                                    <option value="<?=$block->getUrlFilter($item2->getUrlKey())?>"
                                                                                        <?=($currentCategory == $item2->getUrlKey()) ? 'selected' : ''?>>
                                                                                        ------ <?=$item2->getName()?>
                                                                                    </option>
                                                                                <?php
                                                                            }
                                                                        }
                                                                    ?>
                                                                <?php
                                                            }
                                                        }
                                                    ?>
                                                <?php } ?>
                                            </select>
                                        </div>
                                    <?php } ?>
                                </div>
                            </div>

                            <?php if($productTotal > 0){?>
                                <section class="wrap-product wrap-product-load-more">
                                    <?php foreach($productCollections as $item){?>
                                        <?php $url = $item->getProductUrl(); ?>
                                        <div class="it">
                                            <div class="img">
                                                <a href="<?=$url?>"><img class="img-fluid" data-id="<?=$item->getId()?>" src="<?=$block->getImage($item);?>" alt="<?=$item->getName()?>" title="<?=$item->getName()?>"/></a>
                                                <div>
                                                    <a href="<?=$url?>"><?=__('View detail')?></a>|
                                                    <a href="javascript:void(0)" class="add-to-cart" data-product_id="<?=$item->getId()?>"><i class="fa fa-spinner loading-addtocart fa-spin hide"></i> <?=__('Add to cart')?></a>
                                                </div>
                                            </div>
                                            <a href="<?=$url?>"><?=$item->getName()?></a>
                                            <span><?=number_format($item->getPrice())?> VNĐ</span>
                                        </div>
                                    <?php } ?>
                                </section>
                            <?php }else{ ?>
                                <h5 class="mt-5 text-center rotobo-font"><?=__("There're no products")?></h5>
                            <?php } ?>

                            <input type="hidden" name="p" id="last-page-number" value="<?=$lastPageNumber?>"/>

                            <?php if($lastPageNumber > 1){?>
                                <div class="text-center">
                                    <a class="more-masonry btn-load-more-product" href="javascript:void(0)"><i class="fa fa-spinner loading-loadmore fa-spin hide"></i> <?=__('View more')?></a>
                                </div>
                            <?php } ?>
                            
                        </div>
                        <div class="col-12 col-sm-12 col-md-12 col-lg-12 col-xl-12">
                            <?php
                                include ($block->getTemplateFile('DrinksAndCo_CustomizeProduct::product/recent-product-bot.phtml'));
                            ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<!-- Popup response consulted -->
<a class="btn-popup-get-consulted" data-fancybox data-src="#popup-get-consulted" href="javascript:;" style="display: none;"></a>
<section style="display: none;" id="popup-get-consulted">
    <div class="wrap-popup update">
        <div class="text-center">
            <img class="img-fluid" src="<?php echo $this->getViewFileUrl('images/ic-logo-white.jpg'); ?>" alt="DrinksAndCo" title="DrinksAndCo"/>
            <h2><?=__('Your cart has been updated')?></h2>
            <a class="start-shop" href="<?=$block->getInfomationConfirmUrl()?>"><?=__('View your cart')?></a>
            <a class="start-shop btn-close-fancybox" href="javascript:void(0)"><?=__('Continue shopping')?></a>
        </div>
    </div>
</section>

<script type="text/x-magento-init">
    {
        "*": {
            "DrinksAndCo_CustomizeProduct/js/list-product": {
                "action": "<?= $block->getLoadMoreProductUrl()?>",
                "btnLoadMoreProduct": ".btn-load-more-product",
                "pageCurrent": "#last-page-number",
                "actionAddToCart": "<?= $block->getPostActionAddToCartUrl()?>"
            }
        }
    }
</script>
