<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
/** @var \Magento\Contact\Block\ContactForm $block */
?>

<!-- <section class="head-page">
    <div class="container-fluid">
        <div class="row">
            <div class="col-12 col-sm-12 col-md-12 col-lg-12 col-xl-12 text-center">
                <h2><?php echo __('Contact Us');?></h2>
            </div>
        </div>
    </div>
</section> -->

<section>
    <div class="container">
        <div class="row text-center">
            <!-- <div class="col-12 col-sm-12 col-md-12 col-lg-12 col-xl-12">
                <nav class="nav-page">
                    <ol class="list-unstyled">
                        <li><a href="/"><?php echo __('Home');?></a></li>
                        <li class="active"><?php echo __('Contact');?></li>
                    </ol>
                </nav>
                
            </div> -->
            <div class="col-12 col-sm-12 col-md-12 col-lg-12 col-xl-12">
                <section class="contact-page">
                    <h2><?php echo __('Contact Us');?></h2>
                    <div class="info"><?= __('The art of drinking is our playground and we are here to share it.')?></div>
                    <form class="form contact"
                        action="<?= $block->escapeUrl($block->getFormAction()) ?>"
                        id="contact-form"
                        method="post"
                        data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>"
                        data-mage-init='{"validation":{}}'>
                        <div class="row">
                            <div class="col-12 col-sm-12 col-md-6 col-lg-6 col-xl-6">
                                <div class="form-group">
                                    <input name="name" id="name" placeholder="<?= $block->escapeHtml(__('Your Name *')) ?>" title="<?= $block->escapeHtmlAttr(__('Name')) ?>" value="" class="form-control" type="text" data-validate="{required:true}"/>
                                </div>
                            </div>
                            <div class="col-12 col-sm-12 col-md-6 col-lg-6 col-xl-6">
                                <div class="form-group">
                                    <input name="email" id="email" placeholder="<?= $block->escapeHtml(__('Your Email *')) ?>" title="<?= $block->escapeHtmlAttr(__('Email')) ?>" value="" class="form-control" type="email" data-validate="{required:true, 'validate-email':true}"/>
                                </div>
                            </div>
                            <div class="col-12 col-sm-12 col-md-6 col-lg-6 col-xl-6">
                                <div class="form-group">
                                    <input name="phone" id="phone" placeholder="<?= $block->escapeHtml(__('Your phone *')) ?>" title="<?= $block->escapeHtmlAttr(__('Phone')) ?>" value="" class="form-control" type="number" maxlength="10" data-validate="{required:true}"/>
                                </div>
                            </div>
                            <div class="col-12 col-sm-12 col-md-6 col-lg-6 col-xl-6">
                                <div class="form-group">
                                    <input name="address" id="address" placeholder="<?= $block->escapeHtml(__('Your address')) ?>" title="<?= $block->escapeHtmlAttr(__('Address')) ?>" value="" class="form-control" type="text" />
                                </div>
                            </div>
                            <div class="col-12 col-sm-12 col-md-12 col-lg-12 col-xl-12">
                                <div class="form-group">
                                    <textarea name="comment" id="comment" placeholder="<?= $block->escapeHtml(__('Message *')) ?>" title="<?= $block->escapeHtmlAttr(__('What’s on your mind?')) ?>" class="form-control"  rows="3" data-validate="{required:true}"><?= $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getPostValue('comment')) ?></textarea>
                                </div>
                                <button class="btn" type="submit" title="<?= $block->escapeHtmlAttr(__('Send')) ?>" class="action submit primary"><span><?= $block->escapeHtml(__('Send')) ?></span></button>
                            </div>
                        </div>
                    </form>
                </section>
            </div>
        </div>
    </div>
</section>
<!-- End Contact -->