<?php
$collection = $block->getCollection();
$categories = $block->getCatetories();
$categoryId = (int)$this->getRequest()->getParam('category_id', false);
$category = $block->getCurrentCategory();
$lastPageNumber = $collection->getLastPageNumber();
?>
<!-- Head Title -->
<section class="head-page">
    <div class="container-fluid">
        <div class="row">
            <div class="col-12 col-sm-12 col-md-12 col-lg-12 col-xl-12 text-center">
                <h2><?php echo $category->getTitle()?></h2>
            </div>
        </div>
    </div>
</section>
<!--End Head Title -->

<section>
    <div class="container">
        <div class="row text-center">
            <div class="col-12 col-sm-12 col-md-12 col-lg-12 col-xl-12">
                <!-- Nav -->
                <nav class="nav-page">
                    <ol class="list-unstyled">
                        <li><a href="/"><?php echo __('Home'); ?></a></li>
                        <li class='active'><?php echo __('News'); ?></li>
                    </ol>
                </nav>
                <!-- End Nav -->
            </div>
            <div class="col-12 col-sm-12 col-md-12 col-lg-12 col-xl-12">
                <section class="news-page">
                    <div class="news-cate">
                        <?php foreach($categories as $cate): ?>
                            <a class="<?php if($cate->getCategoryId() == $categoryId) echo 'is-checked' ?>"  href="<?php echo $cate->getCategoryUrl()?>"><?php echo $cate->getTitle()?></a>
                        <?php endforeach;?>
                        <!-- <a data-filter=".cocktails" class="is-checked" href="#">COCKTAILS</a>
                        <a data-filter=".category" href="#">category</a>
                        <a data-filter=".lifestyle" href="#">lifestyle</a> -->
                    </div>
                    <?php if (!count($collection)): ?>
                        <div class="message-empty">
                            <div><?php echo __('Have no posts.') ?></div>
                        </div>
                    <?php else: ?>
                    <div class="news-all masonry text-left wrap-news-load-more">
                        <?php  foreach ($collection as $post):  ?>
                            <div class="it">
                                <a href="<?php echo $post->getPostUrlWithCategory($categoryId); ?>">
                                    <img class="img-fluid news-item-img" src="<?php echo $post->getThumbnailUrl(); ?>" alt="<?php echo $post->getTitle() ?>">
                                </a>
                                <div>
                                <?php if ($post->getUpdatedByUser()): ?>
                                    <?php echo __('Posted by %1', $post->getUpdatedByUser()); ?>
                                <?php else: ?>
                                    <?php echo __('Posted by %1', $post->getUser()); ?>
                                <?php endif; ?>  
                                    <?php echo __('%1', $block->formatDate($post->getCreatedAt(), \IntlDateFormatter::MEDIUM, false)); ?>
                                </div>
                                <a href="<?php echo $post->getPostUrlWithCategory($categoryId); ?> ">
                                    <?php echo $post->getTitle(); ?>
                                </a>
                            </div>
                        <?php endforeach;?>
                    </div>

                    <input type="hidden" name="p" id="p" value="2"/>
                    <input type="hidden" name="p" id="last-page-number" value="<?=$lastPageNumber?>"/>

                    <?php if($lastPageNumber > 1){?>
                        <div class="text-center">
                        <a class="more-masonry btn-load-more-news" href="javascript:void(0)"><?=__('View more')?></a>
                        </div>
                    <?php } ?>
                    <?php endif;?>
                </section>
            </div>
        </div>
    </div>
    
</section>


<script type="text/x-magento-init">
    {
        "*": {
            "DrinksAndCo_News/js/list-news-category": {
                "action": "<?= $block->getLoadMoreNews()?>",
                "btnLoadMoreProduct": ".btn-load-more-news",
                "pageCurrent": ".news-page #p"
            }
        }
    }
</script>
