<?php
    $getThumbBrandActive = $block->getThumbBrandActive();
    $topBrands = $block->getTopBrands();
    if($topBrands){
?>

<section class="slider-partner">
    <div><?=$getThumbBrandActive?></div>

    <div>
        <div class="swiper-container">
            <div class="swiper-wrapper">
                <?php foreach($topBrands as $item){?>
                    <div class="swiper-slide">
                        <div class="it">
                            <a href="<?=$item->getUrl()?>">
                                <img src="<?= $item->getImageUrl() ?>" alt="<?= $item->getName()?>" title="<?= $item->getName()?>"/><span></span>
                            </a>
                        </div>
                    </div>
                <?php } ?>
            </div>
        </div>
    </div>
</section>

<?php } ?>