<?php
$helper = $this->helper('DrinksAndCo\History\Helper\Data');
$post = $block->getCurrentPost();
$relatedPost = $block->getRelatedPost();
// foreach($relatedPost as $item)
// {
//     var_dump($item->getTitle());
// }
// var_dump($block->getBaseUrl());
?>
<!-- Head Title -->
<!-- <section class="head-page">
    <div class="container-fluid">
        <div class="row">
            <div class="col-12 col-sm-12 col-md-12 col-lg-12 col-xl-12 text-center">
                <h2><?php echo __('History') ?></h2>
            </div>
        </div>
    </div>
</section> -->
<!--End Head Title -->
<section>
    <div class="container">
        <div class="row">
            <div class="col-12 col-sm-12 col-md-12 col-lg-12 col-xl-12">
                <!-- Nav -->
                <nav class="nav-page">
                    <ol class="list-unstyled">
                        <li><a href="/"><?php echo __('Home'); ?></a></li>
                        <li><a href="<?=$block->getBaseUrl() . __('history')?>"><?=__('History')?></a></li>
                        <li class="active"><?php echo $post->getTitle() ?></li>
                    </ol>
                </nav>
                <!-- End Nav -->
            </div>
            <div class="col-12 col-sm-12 col-md-12 col-lg-12 col-xl-12">
                <section class="history-detail">
                    <div class="img">
                        <img class="img-fluid" src="<?php echo $post->getImageUrl(); ?>" alt="<?php echo $post->getTitle() ?>"/>
                        <!-- <a href="#">
                            <img class="img-fluid" src="images/ic-share.png" alt="" title=""/>
                        </a> -->
                    </div>
                    <?php if ($post->getContent()): ?>
                        <div class="ap-detail">
                            <?php echo $post->getContent(); ?>
                        </div>
                    <?php endif; ?>
                </section>

                <section class="history-relate">
                    <div class="row">
                        <div class="col-12 col-sm-12 col-md-12 col-lg-12 col-xl-12">
                            <h3><?php echo __('Related History');?></h3>
                        </div>

                        <?php foreach($relatedPost as $related):?>
                        <div class="col-12 col-sm-6 col-md-6 col-lg-3 col-xl-3">
                            <div class="it">
                                <a href="<?php
                                    if($related->getCatetories()->getFirstItem()->getUrlKey() != null )
                                        echo $related->getPostUrlWithCategory($related->getCatetories()->getFirstItem()->getUrlKey()); 
                                    else    
                                        echo $related->getPostUrlWithNoCategory(); 
                                ?>">
                                    <img class="img-fluid" src="<?php echo $related->getThumbnailUrl()?>" alt="<?php echo $related->getTitle() ?>" title="<?php echo $related->getTitle() ?>"/>
                                    <span><?php echo $related->getTitle() ?></span>
                                </a>

                                

                            </div>
                        </div>
                        <?php endforeach ;?>
<!--                         
                        <div class="col-12 col-sm-6 col-md-6 col-lg-3 col-xl-3">
                            <div class="it">
                                <a href="#">
                                    <img class="img-fluid" src="images/img-relate.png" alt="" title=""/>
                                    <span>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</span>
                                </a>
                            </div>
                        </div>
                        <div class="col-12 col-sm-6 col-md-6 col-lg-3 col-xl-3">
                            <div class="it">
                                <a href="#">
                                    <img class="img-fluid" src="images/img-relate.png" alt="" title=""/>
                                    <span>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</span>
                                </a>
                            </div>
                        </div>
                        <div class="col-12 col-sm-6 col-md-6 col-lg-3 col-xl-3">
                            <div class="it">
                                <a href="#">
                                    <img class="img-fluid" src="images/img-relate.png" alt="" title=""/>
                                    <span>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</span>
                                </a>
                            </div>
                        </div> -->
                    </div>
                </section>
                
            </div>
        </div>
    </div>
</section>