<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * @var \Magento\Theme\Block\Html\Header\Logo $block
 */
?>
<?php $storeName = $block->getThemeName() ? $block->getThemeName() : $block->getLogoAlt();?>
<span class="action nav-toggle"><span><?= /* @escapeNotVerified */ __('Toggle Nav') ?></span></span>
<?php if ($block->isHomePage()):?>
<strong class="logo">
    <?php else: ?>
    <a class="logo" href="<?= $block->getUrl('') ?>" title="<?= /* @escapeNotVerified */ $storeName ?>">
        <?php endif ?>
        <?php if($block->getUseCustomLogo()):?>
            <img src="<?= /* @escapeNotVerified */ $block->getCustomLogo() ?>"
                 alt="<?= /* @escapeNotVerified */ $block->getLogoAlt() ?>"
                <?= $block->getLogoWidth() ? 'width="' . $block->getLogoWidth() . '"' : '' ?>
                <?= $block->getLogoHeight() ? 'height="' . $block->getLogoHeight() . '"' : '' ?>
            />
        <?php else:?>
            <img src="<?= /* @escapeNotVerified */ $block->getLogoSrc() ?>"
                 alt="<?= /* @escapeNotVerified */ $block->getLogoAlt() ?>"
                <?= $block->getLogoWidth() ? 'width="' . $block->getLogoWidth() . '"' : '' ?>
                <?= $block->getLogoHeight() ? 'height="' . $block->getLogoHeight() . '"' : '' ?>
            />
        <?php endif;?>
        <?php if ($block->isHomePage()):?>
</strong>
<?php else:?>
    </a>
<?php endif?>
