<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Checkout\Block\Cart\Sidebar */
?>
<div id="header-minicart">
    <div data-block="minicart" class="minicart-wrapper">
        <a class="action showcart" href="javascript:void(0)"
           data-bind="scope: 'minicart_content'">
            <i class="fa fa-shopping-basket"></i>
            <span class="text"><?= /* @escapeNotVerified */
                __('My Cart') ?></span>
            <span class="ecg-counter qty empty"
                  data-bind="css: { empty: !!getCartParam('summary_count') == false }, blockLoader: isLoading">
            <span class="counter-number"><!-- ko text: getCartParam('summary_count') --><!-- /ko --></span>
            <span class="counter-label">
            <!-- ko if: getCartParam('summary_count') -->
                <!-- ko text: getCartParam('summary_count') --><!-- /ko -->
                <!-- ko i18n: 'items' --><!-- /ko -->
                <!-- /ko -->
            </span>
        </span>
        </a>
        <?php if ($block->getIsNeedToDisplaySideBar()): ?>
            <div class="block block-minicart"
                 data-role="dropdownDialog"
                 data-mage-init='{"dropdownDialog":{
                "appendTo":"[data-block=minicart]",
                "triggerTarget":".showcart",
                "timeout": "2000",
                "closeOnMouseLeave": false,
                "closeOnEscape": true,
                "triggerClass":"active",
                "parentClass":"active",
                "buttons":[]}}'>

                <div class="minicart-content-header">
                        <span class="title_text"><?= /* @escapeNotVerified */
                            __('Shopping Cart') ?></span>
                    <div class="mini-close" data-action="close" id="btn-minicart-close">
                        <i class="fa fa-close"></i>
                    </div>

                </div>
                <div id="minicart-content-wrapper" data-bind="scope: 'minicart_content'">
                    <!-- ko template: getTemplate() --><!-- /ko -->
                </div>
                <?= $block->getChildHtml('minicart.addons') ?>
            </div>
        <?php endif ?>
        <script>
            window.checkout = <?= /* @escapeNotVerified */ $block->getSerializedConfig() ?>;
        </script>
        <script type="text/x-magento-init">
    {
        "[data-block='minicart']": {
            "Magento_Ui/js/core/app": <?= /* @escapeNotVerified */
            $block->getJsLayout() ?>
        },
        "*": {
            "Magento_Ui/js/block-loader": "<?= /* @escapeNotVerified */
            $block->getViewFileUrl('images/loader-1.gif') ?>"
        }
    }

        </script>
    </div>

</div>


